<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZnZend\Module'                            => __DIR__ . '/Module.php',
    'ZnZend\Model\AbstractEntity'              => __DIR__ . '/src/ZnZend/Model/AbstractEntity.php',
    'ZnZend\View\Helper\ZnZendExcerpt'         => __DIR__ . '/src/ZnZend/View/Helper/ZnZendExcerpt.php',
    'ZnZend\View\Helper\ZnZendFormatBytes'     => __DIR__ . '/src/ZnZend/View/Helper/ZnZendFormatBytes.php',
    'ZnZend\View\Helper\ZnZendFormatDateRange' => __DIR__ . '/src/ZnZend/View/Helper/ZnZendFormatDateRange.php',
    'ZnZend\View\Helper\ZnZendFormatTimeRange' => __DIR__ . '/src/ZnZend/View/Helper/ZnZendFormatTimeRange.php',
);
